# Generated by Django 4.2.7 on 2024-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "남성"), ("Female", "여성")], max_length=10
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("10s", "10대"),
                            ("20s", "20대"),
                            ("30s", "30대"),
                            ("40s", "40대"),
                            ("50s", "50대 이상"),
                        ],
                        max_length=10,
                    ),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sido",
                    models.CharField(
                        choices=[("Seoul", "서울"), ("Busan", "부산"), ("Incheon", "인천")],
                        max_length=20,
                    ),
                ),
                (
                    "travel_style",
                    models.CharField(
                        choices=[
                            ("Adventure", "모험"),
                            ("Relaxation", "휴식"),
                            ("Cultural", "문화체험"),
                            ("City", "도시 여행"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "travel_motive",
                    models.CharField(
                        choices=[
                            ("Leisure", "휴식"),
                            ("Exploration", "탐험"),
                            ("Cultural_experience", "문화체험"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "travel_companions_num",
                    models.CharField(
                        choices=[
                            ("Alone", "혼자"),
                            ("With_family", "가족과"),
                            ("With_friends", "친구와"),
                            ("Group", "단체"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
