# Generated by Django 4.2.7 on 2024-01-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("TripRecommender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("남", "남"), ("여", "여")], max_length=10),
                ),
                (
                    "age",
                    models.IntegerField(
                        choices=[
                            ("1", "10"),
                            ("2", "20"),
                            ("3", "30"),
                            ("4", "40"),
                            ("5", "50"),
                            ("6", "60"),
                        ]
                    ),
                ),
                (
                    "income",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ]
                    ),
                ),
                (
                    "travel_style_1",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_2",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_3",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_4",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_5",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_6",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_7",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_style_8",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ]
                    ),
                ),
                (
                    "travel_motive",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ]
                    ),
                ),
                (
                    "travel_num",
                    models.CharField(
                        choices=[
                            ("1", "1회"),
                            ("2", "2회"),
                            ("3", "3회"),
                            ("4", "4회"),
                            ("5", "5회 이상"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "travel_companions_num",
                    models.CharField(
                        choices=[
                            ("0", "0명"),
                            ("1", "1명"),
                            ("2", "2명"),
                            ("3", "3명"),
                            ("4", "4명"),
                            ("5", "5명이상"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
