# Generated by Django 5.0.1 on 2024-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripRecommender", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouristSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_area_name", models.CharField(max_length=100)),
                ("xcoord", models.FloatField()),
                ("ycoord", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="traveler",
            name="age",
            field=models.IntegerField(
                choices=[
                    ("1", "20"),
                    ("2", "30"),
                    ("3", "40"),
                    ("4", "50"),
                    ("5", "60"),
                ]
            ),
        ),
    ]
