# Generated by Django 5.0.1 on 2024-01-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripRecommender", "0003_touristspot_alter_traveler_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveler",
            name="travel_mission_priority",
            field=models.IntegerField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                default=0,
            ),
        ),
    ]
