# Generated by Django 5.0.1 on 2024-01-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripRecommender", "0004_traveler_travel_mission_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="income",
            field=models.IntegerField(),
        ),
    ]
