# Generated by Django 5.0.1 on 2024-01-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripRecommender", "0005_alter_traveler_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristspot",
            name="main_image",
            field=models.ImageField(blank=True, upload_to="main_images/"),
        ),
    ]
