# Generated by Django 5.0.1 on 2024-01-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripRecommender", "0006_touristspot_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="main_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="SpotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("rcmd_image", models.ImageField(blank=True, upload_to="")),
                ("similarity", models.FloatField()),
                (
                    "tourist_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TripRecommender.touristspot",
                    ),
                ),
            ],
        ),
    ]
